export const dataJson = [
  {
    id: "tt2301451",
    title: "Ozymandias",
    year: "2013",
    rated: "TV-14",
    released: "15 Sep 2013",
    season: "5",
    episode: "14",
    runtime: "48 min",
    genre: "Crime, Drama, Thriller",
    director: "Rian Johnson",
    writer: "Vince Gilligan (created by), Moira Walley-Beckett",
    actors: "Bryan Cranston, Anna Gunn, Aaron Paul, Dean Norris",
    plot: "Walt goes on the run. Jesse is taken hostage. Marie convinces Skyler to tell Walter, Jr. the truth.",
    language: "English",
    country: "USA",
    awards: "N/A",
    poster:
      "https://m.media-amazon.com/images/M/MV5BMTU1MjEwNjQ4MF5BMl5BanBnXkFtZTgwNzI2MTU5NTM@._V1_SX300.jpg",
    ratings: [
      {
        Source: "Internet Movie Database",
        Value: "10.0/10",
      },
    ],
    metascore: "N/A",
    imdbrating: "10.0",
    imdbvotes: "137214",
    imdbid: "tt2301451",
    seriesid: "tt0903747",
    type: "episode",
    response: "True",
  },
  {
    id: "tt4283088",
    title: "Battle of the Bastards",
    year: "2016",
    rated: "TV-MA",
    released: "19 Jun 2016",
    season: "6",
    episode: "9",
    runtime: "60 min",
    genre: "Action, Adventure, Drama, Fantasy",
    director: "Miguel Sapochnik",
    writer:
      'George R.R. Martin (based on "A Song of Ice and Fire" by), David Benioff (created by), D.B. Weiss (created by), David Benioff (written for television by), D.B. Weiss (written for television by)',
    actors: "Peter Dinklage, Kit Harington, Emilia Clarke, Liam Cunningham",
    plot: "Jon and Sansa face Ramsay Bolton on the fields of Winterfell. Daenerys strikes back at her enemies. Theon and Yara arrive in Meereen.",
    language: "English",
    country: "USA",
    awards: "N/A",
    poster:
      "https://m.media-amazon.com/images/M/MV5BZDFiZTNiMmItMDk5ZC00OGZmLTk3NmItODM5ZWE2YWMzZjliXkEyXkFqcGdeQXVyOTMyOTQyNzA@._V1_SX300.jpg",
    ratings: [
      {
        Source: "Internet Movie Database",
        Value: "9.9/10",
      },
    ],
    metascore: "N/A",
    imdbrating: "9.9",
    imdbvotes: "194010",
    imdbid: "tt4283088",
    seriesid: "tt0944947",
    type: "episode",
    response: "True",
  },
  {
    id: "tt4283094",
    title: "The Winds of Winter",
    year: "2016",
    rated: "TV-MA",
    released: "26 Jun 2016",
    season: "6",
    episode: "10",
    runtime: "68 min",
    genre: "Action, Adventure, Drama, Fantasy",
    director: "Miguel Sapochnik",
    writer:
      'George R.R. Martin (based on "A Song of Ice and Fire" by), David Benioff (created by), D.B. Weiss (created by), David Benioff (written for television by), D.B. Weiss (written for television by)',
    actors: "Peter Dinklage, Nikolaj Coster-Waldau, Lena Headey, Kit Harington",
    plot: "Cersei and Loras Tyrell stand trial by the gods. Daenerys prepares to set sail for Westeros. Davos confronts Melisandre. Sam and Gilly arrive in the Citadel. Bran discovers a long-kept secret. Lord Frey has an uninvited guest.",
    language: "English",
    country: "USA",
    awards: "N/A",
    poster:
      "https://m.media-amazon.com/images/M/MV5BMTc0ZjQ5ODctYzRmNC00ZjQ3LWFlZDctN2NjNjY1MTliMjU3L2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyNjkxMjM5Nzc@._V1_SX300.jpg",
    ratings: [
      {
        Source: "Internet Movie Database",
        Value: "9.9/10",
      },
    ],
    metascore: "N/A",
    imdbrating: "9.9",
    imdbvotes: "135728",
    imdbid: "tt4283094",
    seriesid: "tt0944947",
    type: "episode",
    response: "True",
  },
  {
    id: "tt12392504",
    title: "Scam 1992: The Harshad Mehta Story",
    year: "2020",
    rated: "TV-14",
    released: "09 Oct 2020",
    runtime: "54 min",
    genre: "Biography, Crime, Drama",
    director: "N/A",
    writer: "N/A",
    actors: "Pratik Gandhi, Shreya Dhanwanthary, Hemant Kher, Anjali Barot",
    plot: "Set in 1980's and 90's Bombay, it follows the life of Harshad Mehta, a stockbroker who took the stock market to dizzying heights and his catastrophic downfall.",
    language: "Hindi",
    country: "India",
    awards: "1 win.",
    poster:
      "https://m.media-amazon.com/images/M/MV5BNjgxZTMxNmQtZGFkZS00NDUyLTllMzYtOTE0ZjdlMjM1ZWU0XkEyXkFqcGdeQXVyMTAyMTE1MDA1._V1_SX300.jpg",
    ratings: [
      {
        Source: "Internet Movie Database",
        Value: "9.5/10",
      },
    ],
    metascore: "N/A",
    imdbrating: "9.5",
    imdbvotes: "100,785",
    imdbid: "tt12392504",
    type: "series",
    totalseasons: "1",
    response: "True",
  },
  {
    id: "tt5491994",
    title: "Planet Earth II",
    year: "2016",
    rated: "TV-G",
    released: "18 Feb 2017",
    runtime: "298 min",
    genre: "Documentary",
    director: "N/A",
    writer: "N/A",
    actors: "David Attenborough",
    plot: "Wildlife documentary series with David Attenborough, beginning with a look at the remote islands which offer sanctuary to some of the planet's rarest creatures, to the beauty of cities, which are home to humans, and animals..",
    language: "French, English",
    country: "UK, Germany, France, China, USA",
    awards: "Won 2 Primetime Emmys. Another 12 wins & 28 nominations.",
    poster:
      "https://m.media-amazon.com/images/M/MV5BZWYxODViMGYtMGE2ZC00ZGQ3LThhMWUtYTVkNGE3OWU4NWRkL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyMjYwNDA2MDE@._V1_SX300.jpg",
    ratings: [
      {
        Source: "Internet Movie Database",
        Value: "9.5/10",
      },
    ],
    metascore: "N/A",
    imdbrating: "9.5",
    imdbvotes: "101,234",
    imdbid: "tt5491994",
    type: "series",
    totalseasons: "1",
    response: "True",
  },
  {
    id: "tt0903747",
    title: "Breaking Bad",
    year: "2008–2013",
    rated: "TV-MA",
    released: "20 Jan 2008",
    runtime: "49 min",
    genre: "Crime, Drama, Thriller",
    director: "N/A",
    writer: "Vince Gilligan",
    actors: "Bryan Cranston, Aaron Paul, Anna Gunn",
    plot: "A high school chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine in order to secure his family's future.",
    language: "English, Spanish",
    country: "United States",
    awards: "Won 16 Primetime Emmys. 152 wins & 238 nominations total",
    poster:
      "https://m.media-amazon.com/images/M/MV5BMjhiMzgxZTctNDc1Ni00OTIxLTlhMTYtZTA3ZWFkODRkNmE2XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
    ratings: [
      {
        Source: "Internet Movie Database",
        Value: "9.4/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "96%",
      },
    ],
    metascore: "N/A",
    imdbrating: "9.4",
    imdbvotes: "1,519,471",
    imdbid: "tt0903747",
    type: "series",
    totalseasons: "5",
    response: "True",
  },
  {
    id: "tt0185906",
    title: "Band of Brothers",
    year: "2001",
    rated: "TV-MA",
    released: "09 Sep 2001",
    runtime: "594 min",
    genre: "Action, Drama, History",
    director: "N/A",
    writer: "N/A",
    actors: "Scott Grimes, Damian Lewis, Ron Livingston",
    plot: "The story of Easy Company of the U.S. Army 101st Airborne Division, and their mission in World War II Europe, from Operation Overlord, through V-J Day.",
    language: "English, Dutch, French, German, Lithuanian",
    country: "United States, United Kingdom",
    awards: "Won 6 Primetime Emmys. 34 wins & 26 nominations total",
    poster:
      "https://m.media-amazon.com/images/M/MV5BMTI3ODc2ODc0M15BMl5BanBnXkFtZTYwMjgzNjc3._V1_SX300.jpg",
    ratings: [
      {
        Source: "Internet Movie Database",
        Value: "9.4/10",
      },
    ],
    metascore: "N/A",
    imdbrating: "9.4",
    imdbvotes: "387,430",
    imdbid: "tt0185906",
    type: "series",
    totalseasons: "1",
    response: "True",
  },
  {
    id: "tt0795176",
    title: "Planet Earth",
    year: "2006",
    rated: "TV-PG",
    released: "25 Mar 2007",
    runtime: "538 min",
    genre: "Documentary",
    director: "N/A",
    writer: "N/A",
    actors: "David Attenborough, Sigourney Weaver, Thomas Anguti Johnston",
    plot: "Emmy Award-winning, 11 episodes, five years in the making, the most expensive nature documentary series ever commissioned by the BBC, and the first to be filmed in high definition.",
    language: "English",
    country: "United Kingdom",
    awards: "Won 4 Primetime Emmys. 15 wins & 15 nominations total",
    poster:
      "https://m.media-amazon.com/images/M/MV5BNmZlYzIzMTItY2EzYS00YTEyLTg0ZjEtMDMzZjM3ODdhN2UzXkEyXkFqcGdeQXVyNjI0MDg2NzE@._V1_SX300.jpg",
    ratings: [
      {
        Source: "Internet Movie Database",
        Value: "9.4/10",
      },
    ],
    metascore: "N/A",
    imdbrating: "9.4",
    imdbvotes: "170,633",
    imdbid: "tt0795176",
    type: "series",
    totalseasons: "1",
    response: "True",
  },
  {
    id: "tt0111161",
    title: "The Shawshank Redemption",
    year: "1994",
    rated: "R",
    released: "14 Oct 1994",
    runtime: "142 min",
    genre: "Drama",
    director: "Frank Darabont",
    writer: "Stephen King, Frank Darabont",
    actors: "Tim Robbins, Morgan Freeman, Bob Gunton",
    plot: "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
    language: "English",
    country: "United States",
    awards: "Nominated for 7 Oscars. 21 wins & 43 nominations total",
    poster:
      "https://m.media-amazon.com/images/M/MV5BMDFkYTc0MGEtZmNhMC00ZDIzLWFmNTEtODM1ZmRlYWMwMWFmXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg",
    ratings: [
      {
        Source: "Internet Movie Database",
        Value: "9.3/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "91%",
      },
      {
        Source: "Metacritic",
        Value: "80/100",
      },
    ],
    metascore: "80",
    imdbrating: "9.3",
    imdbvotes: "2,400,369",
    imdbid: "tt0111161",
    type: "movie",
    dvd: "15 Aug 2008",
    boxoffice: "$28,699,976",
    production: "Columbia Pictures, Castle Rock Entertainment",
    website: "N/A",
    response: "True",
  },
  {
    id: "tt0944947",
    title: "Game of Thrones",
    year: "2011–2019",
    rated: "TV-MA",
    released: "17 Apr 2011",
    runtime: "57 min",
    genre: "Action, Adventure, Drama",
    director: "N/A",
    writer: "David Benioff, D.B. Weiss",
    actors: "Emilia Clarke, Peter Dinklage, Kit Harington",
    plot: "Nine noble families fight for control over the lands of Westeros, while an ancient enemy returns after being dormant for millennia.",
    language: "English",
    country: "United States, United Kingdom",
    awards: "Won 59 Primetime Emmys. 378 wins & 618 nominations total",
    poster:
      "https://m.media-amazon.com/images/M/MV5BYTRiNDQwYzAtMzVlZS00NTI5LWJjYjUtMzkwNTUzMWMxZTllXkEyXkFqcGdeQXVyNDIzMzcwNjc@._V1_SX300.jpg",
    ratings: [
      {
        Source: "Internet Movie Database",
        Value: "9.3/10",
      },
    ],
    metascore: "N/A",
    imdbrating: "9.3",
    imdbvotes: "1,817,527",
    imdbid: "tt0944947",
    type: "series",
    totalseasons: "8",
    response: "True",
  },
  {
    id: "tt0306414",
    title: "The Wire",
    year: "2002–2008",
    rated: "TV-MA",
    released: "02 Jun 2002",
    runtime: "59 min",
    genre: "Crime, Drama, Thriller",
    director: "N/A",
    writer: "David Simon",
    actors: "Dominic West, John Doman, Deirdre Lovejoy, Wendell Pierce",
    plot: "The Baltimore drug scene, as seen through the eyes of drug dealers and law enforcement.",
    language: "English, Greek, Mandarin, Spanish",
    country: "USA",
    awards:
      "Nominated for 2 Primetime Emmys. Another 16 wins & 52 nominations.",
    poster:
      "https://m.media-amazon.com/images/M/MV5BNTllYzFhMjAtZjExNS00MjM4LWE5YmMtOGFiZGRlOTU5YzJiXkEyXkFqcGdeQXVyNDIzMzcwNjc@._V1_SX300.jpg",
    ratings: [
      {
        Source: "Internet Movie Database",
        Value: "9.3/10",
      },
    ],
    metascore: "N/A",
    imdbrating: "9.3",
    imdbvotes: "292,111",
    imdbid: "tt0306414",
    type: "series",
    totalseasons: "5",
    response: "True",
  },
  {
    id: "tt0417299",
    title: "Avatar: The Last Airbender",
    year: "2005–2008",
    rated: "TV-Y7-FV",
    released: "21 Feb 2005",
    runtime: "23 min",
    genre: "Animation, Action, Adventure, Family, Fantasy, Mystery",
    director: "N/A",
    writer: "Michael Dante DiMartino, Bryan Konietzko",
    actors: "Dee Bradley Baker, Zach Tyler, Mae Whitman, Jack De Sena",
    plot: "In a war-torn world of elemental magic, a young boy reawakens to undertake a dangerous mystic quest to fulfill his destiny as the Avatar, and bring peace to the world.",
    language: "English",
    country: "USA",
    awards: "Won 1 Primetime Emmy. Another 8 wins & 6 nominations.",
    poster:
      "https://m.media-amazon.com/images/M/MV5BODc5YTBhMTItMjhkNi00ZTIxLWI0YjAtNTZmOTY0YjRlZGQ0XkEyXkFqcGdeQXVyODUwNjEzMzg@._V1_SX300.jpg",
    ratings: [
      {
        Source: "Internet Movie Database",
        Value: "9.3/10",
      },
    ],
    metascore: "N/A",
    imdbrating: "9.3",
    imdbvotes: "257,761",
    imdbid: "tt0417299",
    type: "series",
    totalseasons: "3",
    response: "True",
  },
  {
    id: "tt2395695",
    title: "Cosmos: A Spacetime Odyssey",
    year: "2014",
    rated: "TV-PG",
    released: "09 Mar 2014",
    runtime: "557 min",
    genre: "Documentary",
    director: "N/A",
    writer: "N/A",
    actors: "Neil deGrasse Tyson, Stoney Emshwiller, Piotr Michael",
    plot: "An exploration of our discovery of the laws of nature and coordinates in space and time.",
    language: "English",
    country: "United States",
    awards: "Won 4 Primetime Emmys. 16 wins & 23 nominations total",
    poster:
      "https://m.media-amazon.com/images/M/MV5BZTk5OTQyZjYtMDk3Yy00YjhmLWE2MTYtZmY4NTg1YWUzZTQ0XkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_SX300.jpg",
    ratings: [
      {
        Source: "Internet Movie Database",
        Value: "9.3/10",
      },
    ],
    metascore: "N/A",
    imdbrating: "9.3",
    imdbvotes: "113,279",
    imdbid: "tt2395695",
    type: "series",
    totalseasons: "1",
    response: "True",
  },
  {
    id: "tt0068646",
    title: "The Godfather",
    year: "1972",
    rated: "R",
    released: "24 Mar 1972",
    runtime: "175 min",
    genre: "Crime, Drama",
    director: "Francis Ford Coppola",
    writer:
      "Mario Puzo (screenplay by), Francis Ford Coppola (screenplay by), Mario Puzo (based on the novel by)",
    actors: "Marlon Brando, Al Pacino, James Caan, Richard S. Castellano",
    plot: "An organized crime dynasty's aging patriarch transfers control of his clandestine empire to his reluctant son.",
    language: "English, Italian, Latin",
    country: "USA",
    awards: "Won 3 Oscars. Another 29 wins & 30 nominations.",
    poster:
      "https://m.media-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWJmNWYtYzZlODY3ZTk3OTFlXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
    ratings: [
      {
        Source: "Internet Movie Database",
        Value: "9.2/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "97%",
      },
      {
        Source: "Metacritic",
        Value: "100/100",
      },
    ],
    metascore: "100",
    imdbrating: "9.2",
    imdbvotes: "1,657,705",
    imdbid: "tt0068646",
    type: "movie",
    dvd: "01 Aug 2013",
    boxoffice: "$134,966,411",
    production: "Paramount Pictures",
    website: "N/A",
    response: "True",
  },
  {
    id: "tt2861424",
    title: "Rick and Morty",
    year: "2013–",
    rated: "TV-MA",
    released: "02 Dec 2013",
    runtime: "23 min",
    genre: "Animation, Adventure, Comedy, Sci-Fi",
    director: "N/A",
    writer: "Dan Harmon, Justin Roiland",
    actors: "Justin Roiland, Chris Parnell, Spencer Grammer, Sarah Chalke",
    plot: "An animated series that follows the exploits of a super scientist and his not-so-bright grandson.",
    language: "English",
    country: "USA",
    awards: "Won 2 Primetime Emmys. Another 16 wins & 24 nominations.",
    poster:
      "https://m.media-amazon.com/images/M/MV5BZjRjOTFkOTktZWUzMi00YzMyLThkMmYtMjEwNmQyNzliYTNmXkEyXkFqcGdeQXVyNzQ1ODk3MTQ@._V1_SX300.jpg",
    ratings: [
      {
        Source: "Internet Movie Database",
        Value: "9.2/10",
      },
    ],
    metascore: "N/A",
    imdbrating: "9.2",
    imdbvotes: "390,401",
    imdbid: "tt2861424",
    type: "series",
    totalseasons: "5",
    response: "True",
  },
  {
    id: "tt0141842",
    title: "The Sopranos",
    year: "1999–2007",
    rated: "TV-MA",
    released: "10 Jan 1999",
    runtime: "55 min",
    genre: "Crime, Drama",
    director: "N/A",
    writer: "David Chase",
    actors: "James Gandolfini, Lorraine Bracco, Edie Falco",
    plot: "New Jersey mob boss Tony Soprano deals with personal and professional issues in his home and business life that affect his mental state, leading him to seek professional psychiatric counseling.",
    language: "English, Italian, Russian",
    country: "United States",
    awards: "Won 21 Primetime Emmys. 120 wins & 309 nominations total",
    poster:
      "https://m.media-amazon.com/images/M/MV5BZGJjYzhjYTYtMDBjYy00OWU1LTg5OTYtNmYwOTZmZjE3ZDdhXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_SX300.jpg",
    ratings: [
      {
        Source: "Internet Movie Database",
        Value: "9.2/10",
      },
    ],
    metascore: "N/A",
    imdbrating: "9.2",
    imdbvotes: "314,362",
    imdbid: "tt0141842",
    type: "series",
    totalseasons: "6",
    response: "True",
  },
  {
    id: "tt1475582",
    title: "Sherlock",
    year: "2010–2017",
    rated: "TV-14",
    released: "24 Oct 2010",
    runtime: "88 min",
    genre: "Crime, Drama, Mystery, Thriller",
    director: "N/A",
    writer: "Mark Gatiss, Steven Moffat",
    actors: "Benedict Cumberbatch, Martin Freeman, Una Stubbs, Rupert Graves",
    plot: "A modern update finds the famous sleuth and his doctor partner solving crime in 21st century London.",
    language: "English",
    country: "UK, USA",
    awards: "Won 9 Primetime Emmys. Another 83 wins & 183 nominations.",
    poster:
      "https://m.media-amazon.com/images/M/MV5BMWY3NTljMjEtYzRiMi00NWM2LTkzNjItZTVmZjE0MTdjMjJhL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyNTQ4NTc5OTU@._V1_SX300.jpg",
    ratings: [
      {
        Source: "Internet Movie Database",
        Value: "9.1/10",
      },
    ],
    metascore: "N/A",
    imdbrating: "9.1",
    imdbvotes: "824,834",
    imdbid: "tt1475582",
    type: "series",
    totalseasons: "4",
    response: "True",
  },
  {
    id: "tt1355642",
    title: "Fullmetal Alchemist: Brotherhood",
    year: "2009–2012",
    rated: "TV-14",
    released: "09 Apr 2009",
    runtime: "24 min",
    genre: "Animation, Action, Adventure, Comedy, Drama, Fantasy, Sci-Fi",
    director: "N/A",
    writer: "Hiromu Arakawa",
    actors: "Kent Williams, Iemasa Kayumi, Vic Mignogna, Muriel Hofmann",
    plot: "Two brothers search for a Philosopher's Stone after an attempt to revive their deceased mother goes awry and leaves them in damaged physical forms.",
    language: "Japanese",
    country: "Japan",
    awards: "3 wins & 4 nominations.",
    poster:
      "https://m.media-amazon.com/images/M/MV5BZmEzN2YzOTItMDI5MS00MGU4LWI1NWQtOTg5ZThhNGQwYTEzXkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_SX300.jpg",
    ratings: [
      {
        Source: "Internet Movie Database",
        Value: "9.1/10",
      },
    ],
    metascore: "N/A",
    imdbrating: "9.1",
    imdbvotes: "129,368",
    imdbid: "tt1355642",
    type: "series",
    totalseasons: "1",
    response: "True",
  },
  {
    id: "tt0468569",
    title: "The Dark Knight",
    year: "2008",
    rated: "PG-13",
    released: "18 Jul 2008",
    runtime: "152 min",
    genre: "Action, Crime, Drama, Thriller",
    director: "Christopher Nolan",
    writer:
      "Jonathan Nolan (screenplay), Christopher Nolan (screenplay), Christopher Nolan (story), David S. Goyer (story), Bob Kane (characters)",
    actors: "Christian Bale, Heath Ledger, Aaron Eckhart, Michael Caine",
    plot: "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
    language: "English, Mandarin",
    country: "USA, UK",
    awards: "Won 2 Oscars. Another 157 wins & 163 nominations.",
    poster:
      "https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_SX300.jpg",
    ratings: [
      {
        Source: "Internet Movie Database",
        Value: "9.0/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "94%",
      },
      {
        Source: "Metacritic",
        Value: "84/100",
      },
    ],
    metascore: "84",
    imdbrating: "9.0",
    imdbvotes: "2,353,974",
    imdbid: "tt0468569",
    type: "movie",
    dvd: "14 Jun 2010",
    boxoffice: "$534,858,444",
    production: "Syncopy",
    website: "N/A",
    response: "True",
  },
  {
    id: "tt0071562",
    title: "The Godfather: Part II",
    year: "1974",
    rated: "R",
    released: "18 Dec 1974",
    runtime: "202 min",
    genre: "Crime, Drama",
    director: "Francis Ford Coppola",
    writer:
      "Francis Ford Coppola (screenplay by), Mario Puzo (screenplay by), Mario Puzo (based on the novel by)",
    actors: "Al Pacino, Robert Duvall, Diane Keaton, Robert De Niro",
    plot: "The early life and career of Vito Corleone in 1920s New York City is portrayed, while his son, Michael, expands and tightens his grip on the family crime syndicate.",
    language: "English, Italian, Spanish, Latin, Sicilian",
    country: "USA",
    awards: "Won 6 Oscars. Another 11 wins & 20 nominations.",
    poster:
      "https://m.media-amazon.com/images/M/MV5BMWMwMGQzZTItY2JlNC00OWZiLWIyMDctNDk2ZDQ2YjRjMWQ0XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
    ratings: [
      {
        Source: "Internet Movie Database",
        Value: "9.0/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "96%",
      },
      {
        Source: "Metacritic",
        Value: "90/100",
      },
    ],
    metascore: "90",
    imdbrating: "9.0",
    imdbvotes: "1,152,413",
    imdbid: "tt0071562",
    type: "movie",
    dvd: "01 Aug 2013",
    boxoffice: "$47,834,595",
    production: "Paramount Pictures, Coppola Company",
    website: "N/A",
    response: "True",
  },
  {
    id: "tt0050083",
    title: "12 Angry Men",
    year: "1957",
    rated: "Approved",
    released: "10 Apr 1957",
    runtime: "96 min",
    genre: "Crime, Drama",
    director: "Sidney Lumet",
    writer: "Reginald Rose",
    actors: "Henry Fonda, Lee J. Cobb, Martin Balsam",
    plot: "A jury holdout attempts to prevent a miscarriage of justice by forcing his colleagues to reconsider the evidence.",
    language: "English",
    country: "United States",
    awards: "Nominated for 3 Oscars. 17 wins & 13 nominations total",
    poster:
      "https://m.media-amazon.com/images/M/MV5BMWU4N2FjNzYtNTVkNC00NzQ0LTg0MjAtYTJlMjFhNGUxZDFmXkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_SX300.jpg",
    ratings: [
      {
        Source: "Internet Movie Database",
        Value: "9.0/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "100%",
      },
      {
        Source: "Metacritic",
        Value: "96/100",
      },
    ],
    metascore: "96",
    imdbrating: "9.0",
    imdbvotes: "707,719",
    imdbid: "tt0050083",
    type: "movie",
    dvd: "N/A",
    boxoffice: "N/A",
    production: "Orion-Nova Pictures",
    website: "N/A",
    response: "True",
  },
  {
    id: "tt14392248",
    title: "Aspirants",
    year: "2021–",
    rated: "N/A",
    released: "07 Apr 2021",
    runtime: "45 min",
    genre: "Drama",
    director: "N/A",
    writer: "Arunabh Kumar, Shreyansh Pandey",
    actors:
      "Naveen Kasturia, Shivankit Singh Parihar, Abhilash Thapliyal, Sunny Hinduja",
    plot: "Aspirants is a story of 3 friends - Abhilash, Shwetketu(SK) and Guri. The story revolves around the past and the present time where the past captures the struggle and the drama behind the ...",
    language: "Hindi",
    country: "India",
    awards: "N/A",
    poster:
      "https://m.media-amazon.com/images/M/MV5BNWRkMjA0NjItMmViYS00MDQyLTgyMWYtOWFmOTA4NmU5MjRjXkEyXkFqcGdeQXVyNDY4NjAxNTc@._V1_SX300.jpg",
    ratings: [
      {
        Source: "Internet Movie Database",
        Value: "9.0/10",
      },
    ],
    metascore: "N/A",
    imdbrating: "9.0",
    imdbvotes: "203,094",
    imdbid: "tt14392248",
    type: "series",
    totalseasons: "1",
    response: "True",
  },
  {
    id: "tt0877057",
    title: "Death Note",
    year: "2006–2007",
    rated: "TV-14",
    released: "21 Oct 2007",
    runtime: "24 min",
    genre: "Animation, Crime, Drama, Fantasy, Mystery, Thriller",
    director: "N/A",
    writer: "N/A",
    actors: "Mamoru Miyano, Brad Swaile, Vincent Tong, Ryô Naitô",
    plot: "An intelligent high school student goes on a secret crusade to eliminate criminals from the world after discovering a notebook capable of killing anyone whose name is written into it.",
    language: "Japanese",
    country: "Japan",
    awards: "2 wins & 1 nomination.",
    poster:
      "https://m.media-amazon.com/images/M/MV5BODkzMjhjYTQtYmQyOS00NmZlLTg3Y2UtYjkzN2JkNmRjY2FhXkEyXkFqcGdeQXVyNTM4MDQ5MDc@._V1_SX300.jpg",
    ratings: [
      {
        Source: "Internet Movie Database",
        Value: "9.0/10",
      },
    ],
    metascore: "N/A",
    imdbrating: "9.0",
    imdbvotes: "252,507",
    imdbid: "tt0877057",
    type: "series",
    totalseasons: "1",
    response: "True",
  },
  {
    id: "tt0303461",
    title: "Firefly",
    year: "2002–2003",
    rated: "TV-14",
    released: "20 Sep 2002",
    runtime: "44 min",
    genre: "Adventure, Drama, Sci-Fi",
    director: "N/A",
    writer: "Joss Whedon",
    actors: "Nathan Fillion, Gina Torres, Alan Tudyk, Morena Baccarin",
    plot: "Five hundred years in the future, a renegade crew aboard a small spacecraft tries to survive as they travel the unknown parts of the galaxy and evade warring factions as well as authority agents out to get them.",
    language: "English, Mandarin",
    country: "USA",
    awards: "Won 1 Primetime Emmy. Another 4 wins & 8 nominations.",
    poster:
      "https://m.media-amazon.com/images/M/MV5BOTcwNzkwMDItZmM1OC00MmQ2LTgxYjgtOTNiNDgxZDAxMjk0XkEyXkFqcGdeQXVyNDQ0MTYzMDA@._V1_SX300.jpg",
    ratings: [
      {
        Source: "Internet Movie Database",
        Value: "9.0/10",
      },
    ],
    metascore: "N/A",
    imdbrating: "9.0",
    imdbvotes: "246,779",
    imdbid: "tt0303461",
    type: "series",
    totalseasons: "1",
    response: "True",
  },
  {
    id: "tt2560140",
    title: "Attack on Titan",
    year: "2013–2021",
    rated: "TV-MA",
    released: "28 Sep 2013",
    runtime: "24 min",
    genre: "Animation, Action, Adventure, Drama, Fantasy, Horror",
    director: "N/A",
    writer: "N/A",
    actors: "Yûki Kaji, Marina Inoue, Josh Grelle, Yui Ishikawa",
    plot: "After his hometown is destroyed and his mother is killed, young Eren Jaeger vows to cleanse the earth of the giant humanoid Titans that have brought humanity to the brink of extinction.",
    language: "Japanese",
    country: "Japan",
    awards: "10 wins & 15 nominations.",
    poster:
      "https://m.media-amazon.com/images/M/MV5BMTY5ODk1NzUyMl5BMl5BanBnXkFtZTgwMjUyNzEyMTE@._V1_SX300.jpg",
    ratings: [
      {
        Source: "Internet Movie Database",
        Value: "9.0/10",
      },
    ],
    metascore: "N/A",
    imdbrating: "9.0",
    imdbvotes: "228,458",
    imdbid: "tt2560140",
    type: "series",
    totalseasons: "4",
    response: "True",
  },
  {
    id: "tt0110912",
    title: "Pulp Fiction",
    year: "1994",
    rated: "R",
    released: "14 Oct 1994",
    runtime: "154 min",
    genre: "Crime, Drama",
    director: "Quentin Tarantino",
    writer:
      "Quentin Tarantino (stories), Roger Avary (stories), Quentin Tarantino",
    actors: "Tim Roth, Amanda Plummer, Laura Lovelace, John Travolta",
    plot: "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
    language: "English, Spanish, French",
    country: "USA",
    awards: "Won 1 Oscar. Another 69 wins & 75 nominations.",
    poster:
      "https://m.media-amazon.com/images/M/MV5BNGNhMDIzZTUtNTBlZi00MTRlLWFjM2ItYzViMjE3YzI5MjljXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
    ratings: [
      {
        Source: "Internet Movie Database",
        Value: "8.9/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "92%",
      },
      {
        Source: "Metacritic",
        Value: "94/100",
      },
    ],
    metascore: "94",
    imdbrating: "8.9",
    imdbvotes: "1,861,736",
    imdbid: "tt0110912",
    type: "movie",
    dvd: "21 Apr 2016",
    boxoffice: "$107,928,762",
    production: "A Band Apart, Miramax Films, Jersey Films",
    website: "N/A",
    response: "True",
  },
  {
    id: "tt0167260",
    title: "The Lord of the Rings: The Return of the King",
    year: "2003",
    rated: "PG-13",
    released: "17 Dec 2003",
    runtime: "201 min",
    genre: "Action, Adventure, Drama, Fantasy",
    director: "Peter Jackson",
    writer:
      "J.R.R. Tolkien (novel), Fran Walsh (screenplay), Philippa Boyens (screenplay), Peter Jackson (screenplay)",
    actors: "Noel Appleby, Ali Astin, Sean Astin, David Aston",
    plot: "Gandalf and Aragorn lead the World of Men against Sauron's army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.",
    language: "English, Quenya, Old English, Sindarin",
    country: "New Zealand, USA",
    awards: "Won 11 Oscars. Another 198 wins & 124 nominations.",
    poster:
      "https://m.media-amazon.com/images/M/MV5BNzA5ZDNlZWMtM2NhNS00NDJjLTk4NDItYTRmY2EwMWZlMTY3XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
    ratings: [
      {
        Source: "Internet Movie Database",
        Value: "8.9/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "93%",
      },
      {
        Source: "Metacritic",
        Value: "94/100",
      },
    ],
    metascore: "94",
    imdbrating: "8.9",
    imdbvotes: "1,671,597",
    imdbid: "tt0167260",
    type: "movie",
    dvd: "06 Apr 2010",
    boxoffice: "$377,845,905",
    production: "New Line Cinema, Saul Zaentz Company",
    website: "N/A",
    response: "True",
  },
  {
    id: "tt0108052",
    title: "Schindler's List",
    year: "1993",
    rated: "R",
    released: "04 Feb 1994",
    runtime: "195 min",
    genre: "Biography, Drama, History",
    director: "Steven Spielberg",
    writer: "Thomas Keneally (book), Steven Zaillian (screenplay)",
    actors: "Liam Neeson, Ben Kingsley, Ralph Fiennes, Caroline Goodall",
    plot: "In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.",
    language: "English, Hebrew, German, Polish, Latin",
    country: "USA",
    awards: "Won 7 Oscars. Another 85 wins & 49 nominations.",
    poster:
      "https://m.media-amazon.com/images/M/MV5BNDE4OTMxMTctNmRhYy00NWE2LTg3YzItYTk3M2UwOTU5Njg4XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg",
    ratings: [
      {
        Source: "Internet Movie Database",
        Value: "8.9/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "98%",
      },
      {
        Source: "Metacritic",
        Value: "94/100",
      },
    ],
    metascore: "94",
    imdbrating: "8.9",
    imdbvotes: "1,235,435",
    imdbid: "tt0108052",
    type: "movie",
    dvd: "05 Mar 2013",
    boxoffice: "$96,898,818",
    production: "Universal Pictures, Amblin Entertainment",
    website: "N/A",
    response: "True",
  },
  {
    id: "tt0108778",
    title: "Friends",
    year: "1994–2004",
    rated: "TV-PG",
    released: "22 Sep 1994",
    runtime: "22 min",
    genre: "Comedy, Romance",
    director: "N/A",
    writer: "David Crane, Marta Kauffman",
    actors: "Jennifer Aniston, Courteney Cox, Lisa Kudrow, Matt LeBlanc",
    plot: "Follows the personal and professional lives of six twenty to thirty-something-year-old friends living in Manhattan.",
    language: "English, Spanish, Italian, French, Dutch, Hebrew",
    country: "USA",
    awards: "Won 6 Primetime Emmys. Another 71 wins & 220 nominations.",
    poster:
      "https://m.media-amazon.com/images/M/MV5BNDVkYjU0MzctMWRmZi00NTkxLTgwZWEtOWVhYjZlYjllYmU4XkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_SX300.jpg",
    ratings: [
      {
        Source: "Internet Movie Database",
        Value: "8.9/10",
      },
    ],
    metascore: "N/A",
    imdbrating: "8.9",
    imdbvotes: "851,580",
    imdbid: "tt0108778",
    type: "series",
    totalseasons: "10",
    response: "True",
  },
];
